apiVersion: 1.0
metadata:
  codeName: "com.hedon_haven.pimpbunny"
  prettyName: "PimpBunny"
  version: v0.1.2
  developer: "angel4833"
  contactEmail: "angel4833@example.com"
  issueTrackerUrl: "https://github.com/angel4833/pimpbunny-plugin/issues"
  description: "PimpBunny provider plugin for Hedon Haven"
  updateUrl: "https://github.com/angel4833/pimpbunny-plugin/releases/latest/download/update.yaml"

providerData:
  iconUrl: "https://pimpbunny.com/favicon.ico"
  serviceUrl: "https://pimpbunny.com"
  handleUrls:
    - "https://pimpbunny.com/"
    - "https://pimpbunny.com/videos/"
    - "https://pimpbunny.com/search"
    - "https://pimpbunny.com/onlyfans-creators/"

initialPageCounts:
  initialHomePage: 0
  initialSearchResultsPage: 0
  initialCommentsPage: 0
  initialVideoSuggestionsPage: 0
  initialAuthorVideosPage: 0
